### ISSUE TITLE
Change Text - Recover Your Investment in 3 – 6 Months

### ISSUE THREAD

**Issue by glenkow** [GitGuild/tigoctm#27]
We need to ensure we are not misrepresenting this number. we could use

Recover Your Investment in 6 - 9 Months

Recover Your Investment in 7.5 Months

Or...?

**Comment by isysd** [comment]
I think 6-9 is perfect. 7.5 is just the median, but realistically it will be a range. Some may recover it within 3, potentially. :)

**Comment by isysd** [comment]
`find ./ -type f | xargs sed -i 's/3 - 6/3 - 9/'`
