### ISSUE TITLE
Home page mockup

### ISSUE THREAD

**Issue by isysd** [GitGuild/tigoctm#6]
Mock up the home page, improving the content layout. Also apply the Tigo colors instead of those which were copied over from deginner.com.

 + [ ] Slider for products
 + [ ] Slider for network
 + [ ] Tigo color scheme
 + [ ] Doesn't look like a copy of deginner.com

**Comment by mobymarto** [comment]
@isysd Can you help me providing the products and content layout for TigoCTM?

**Comment by luisvillara** [comment]
The image on `how.md` file is not found

**Comment by isysd** [comment]
@luisvillara it is under construction. Please work around it for now.

**Comment by mobymarto** [comment]
@isysd invis.io/Y668JREHX

**Comment by luisvillara** [comment]
This is the mockup, hope you like it.

![home_menu_desktop_hd](https://cloud.githubusercontent.com/assets/2540621/13404724/3f574476-deed-11e5-971e-8e23bef7d222.png)

**Comment by isysd** [comment]
Hi guys, we're making feedback via invisionapp. Also wanted to share a draft of the infographic. I think that it is inspirational for what we can do better on the website. The top section is particularly convincing at selling machines!

![tigo-ctm](https://cloud.githubusercontent.com/assets/1041868/13515184/63058ce2-e17d-11e5-8689-fba111aad017.png)

**Comment by d3brouille** [comment]
@isysd, @cindy-zimmerman what is the plan for the infographic? Will it be linked from tigoctm.com?

Why, how, what.

Why:
1. The fastest and easiest way to own a Cryptocurrency Teller Machine

**Comment by d3brouille** [comment]
@isysd @cindy-zimmerman 

I agree that the top part of the infographic is a strong argument that catches one's attention immediately.

Why:
1. The fastest and easiest way to own a cryptocurrency teller machine.

How:
What:

**Comment by d3brouille** [comment]
@isysd @cindy-zimmerman

I agree that the top part of the infographic is a strong argument that catches one's attention immediately and would be motivation to read further.  I recommend implementing a 'Why, How, What' logical structure that blends the content from the infographic with the current version of the website content.  

Each of the highlighted sections below would be linked in the header.

`Above the fold`
* Start with the logo, then follow with the top section of the infographic, i.e., from `The fastest and easiest way to own a cryptocurrency teller machine.` to `Each Tigo CTM comes with additional cryptocurrency support, giving your users a full range of options.`

`How it Works`
* Adapt or reuse the `How it works?` section of the infographic.
* Include the costs here

`Products`
* Products section, that also includes more information about Lamassu

`About`
* Tigo using current about copy checked in as basis

`Network`
* Tigo's network
    * Deginner
          * Dash integration
    * Coinapult
    * Crypto Capital

`Contact`
* Contact form
    * Link to F.A.Q. page

What are your thoughts about this approach?

**Comment by isysd** [comment]
This sounds like a good approach, @d3brouille. I agree the content is mostly there and just needs to be organized logically. :+1:

**Comment by d3brouille** [comment]
@mobymarto @luisvillara ,

Will you be submitting a revised mockup with regard to the subsequent comments since the [initial version](https://github.com/deginner/tigoctm/issues/6#issuecomment-190324688) you submitted?

**Comment by luisvillara** [comment]
Hi @isysd this is the mockup with all changes, let me know if we have to change something else.

Invision link: https://invis.io/V768JRQ8Y

![home_menu_desktop_hd](https://cloud.githubusercontent.com/assets/2540621/14965892/a4ea62a6-1079-11e6-8d44-18f47bf5cf7d.png)

**Comment by isysd** [comment]
@d3brouille @luisvillara there is so much good content and design here, but it is not being put together nicely. This deserves more thought than copying and pasting A inside of B. The most important section of all (the top 3 points in the infographic) were lost entirely, when they should be prominently featured.

**Comment by luisvillara** [comment]
Hello @isysd here is the mockup with the infographics elements :D hope you like it!

![home_menu_desktop_hd](https://cloud.githubusercontent.com/assets/2540621/15475985/c970a146-20da-11e6-8113-f4cb37eb3a83.png)

**Comment by d3brouille** [comment]
@luisvillara the mockup above is very close to the specification I described in the comment on [Apr 15](https://github.com/deginner/tigoctm/issues/6#issuecomment-210636041).  Nevertheless, we've decided to pivot the focus the site.

The original specification makes the assumption the client is already looking for a CTM, but discouraged by the technical and network constraints.  We've decided to shift the the ideal client/visitor to someone who is looking for a residual income business opportunity who probably has some concept of Bitcoin and Crypto Currencies, but isn't an expert.

A new specification has been published in wireframe format and is available for viewing [here](https://glenkowalski.mybalsamiq.com/projects/tigo/prototype/Tigo%20Main%20Page?key=cc456bc951b543236ddc56491f4b42bcf3580b42). Please take another pass at this task based on the new specification.

Please let me know if you have any questions or if there are any points I can clarify.

**Comment by isysd** [comment]
@luisvillara please post a screenshot of your new draft. We will review the screenshot while you prepare to re-submit the PR with only Hugo.
